
version: "3.9"

services:

  wapp2:
    build: ./wapp
    ports:
      - "8096:8080"
    environment:
      - DOCK_HOST=$HOSTNAME
    volumes:
      - "wapp_vol:/var/log/wapp"
    hostname: wapp2

    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M

  bb2:
    image: busybox
    command: dd if=/dev/zero of=/dev/null bs=4096
    depends_on:
      - wapp2

    deploy:
      resources:
        limits:
          cpus: '0.060'
          memory: 10M  


networks:
  default:
    name: mynet
    ipam:
      driver: default
      config: 
        - subnet: 172.30.35.0/24
          gateway: 172.30.35.1      
          

volumes:
  vol2:
  wapp_vol:
