version: "3.9"

services:
  gst0:
    image: docker/getting-started
    ports:
      - 8091:80
    environment:
      - DATA=test data
      - VERSION=1.2.3
 
  wapp:
    image: a0z9/dock:wapp.0.5
    ports:
      - 8075:8080
    environment: 
      - DOCK_HOST=$HOSTNAME    

