version: "3.9"

services:
  gst0:
    image: docker/getting-started
    ports:
      - 8051:80
    environment:
      - DATA=test data
      - VERSION=1.2.3
    depends_on: 
      - wapp


  wapp:
    image: a0z9/dock:wapp.0.5
    ports:
      - 8055:8080
    environment: 
      - DOCK_HOST=$HOSTNAME
    volumes:
      - vol1:/var/data        

  bb:
    image: busybox
    command: dd if=/dev/random of=/dev/null bs=4096
    depends_on: 
      - gst0
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 25M

volumes:
  vol1:

